# Dependencies
markdown:         redcarpet
redcarpet:
   extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            SGP
tagline:          'Student Growth Percentiles'
url:              https://sgp.io
shorturl:         sgp.io

author:
  name:           'Damian Betebenner'
  url:            https://twitter.com/dbetebenner

paginate:         2

version:          1.3-0.0

github:
  repo:           https://github.com/dbetebenner/SGP

gems:
   - jekyll-redirect-from

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}

url: https://sgp.io
enforce_ssl: sgp.io
